"""use singular project_id

Revision ID: db73b2ed4b55
Revises: 1b11e91cd385
Create Date: 2023-06-23 10:31:54.368001

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db73b2ed4b55"
down_revision = "1b11e91cd385"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archives", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.drop_constraint(
        "fk_archives_projects_id_projects", "archives", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_archives_project_id_projects"),
        "archives",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_column("archives", "projects_id")
    op.add_column("files", sa.Column("project_id", sa.Uuid(), nullable=False))
    op.drop_constraint("fk_files_projects_id_projects", "files", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_files_project_id_projects"),
        "files",
        "projects",
        ["project_id"],
        ["id"],
    )
    op.drop_column("files", "projects_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files",
        sa.Column("projects_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_files_project_id_projects"), "files", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_files_projects_id_projects", "files", "projects", ["projects_id"], ["id"]
    )
    op.drop_column("files", "project_id")
    op.add_column(
        "archives",
        sa.Column("projects_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_archives_project_id_projects"), "archives", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_archives_projects_id_projects",
        "archives",
        "projects",
        ["projects_id"],
        ["id"],
    )
    op.drop_column("archives", "project_id")
    # ### end Alembic commands ###
