"""unnamed

Revision ID: b9fb42d00930
Revises: be9763d49e5f
Create Date: 2024-09-23 13:50:21.160514

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9fb42d00930"
down_revision = "be9763d49e5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("webdav_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "webdav_path")
    # ### end Alembic commands ###
