"""archives-completed-on

Revision ID: be9763d49e5f
Revises: 4d766c1cc6a3
Create Date: 2024-06-06 18:04:36.401616

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "be9763d49e5f"
down_revision = "4d766c1cc6a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("archive", sa.Column("completed_on", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("archive", "completed_on")
    # ### end Alembic commands ###
