"""order

Revision ID: ffa3ecb69bc6
Revises: b9fb42d00930
Create Date: 2024-10-09 11:42:32.890617

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ffa3ecb69bc6"
down_revision = "b9fb42d00930"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("order", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "order")
    # ### end Alembic commands ###
